%Values for PD
ALLERP = pop_geterpvalues( ALLERP, [ 200 500],  3,  35 , 'Baseline', 'pre', 'Erpsets',  1:17, 'FileFormat', 'wide', 'Filename',...
 '/Volumes/REDWOOD/Blackbird/Intern Folder/ERP/22q ERPs/DT 22q/DT_happy_measures_22q_PD.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areap',...
 'Resolution',  3 );