%rereferenceing, do on both ICA and non ICA versions
EEG = pop_eegchanoperator( EEG, {  'nch1 = ch1 - ( (ch10 + ch21)/2 ) Label Fp1',  'nch2 = ch2 - ( (ch10 + ch21)/2 ) Label Fz',...
  'nch3 = ch3 - ( (ch10 + ch21)/2 ) Label F3',  'nch4 = ch4 - ( (ch10 + ch21)/2 ) Label F7',  'nch5 = ch5 - ( (ch10 + ch21)/2 ) Label FT9',...
  'nch6 = ch6 - ( (ch10 + ch21)/2 ) Label FC5',  'nch7 = ch7 - ( (ch10 + ch21)/2 ) Label FC1',  'nch8 = ch8 - ( (ch10 + ch21)/2 ) Label C3',...
  'nch9 = ch9 - ( (ch10 + ch21)/2 ) Label T7',  'nch10 = ch10 - ( (ch10 + ch21)/2 ) Label TP9',  'nch11 = ch11 - ( (ch10 + ch21)/2 ) Label CP5',...
  'nch12 = ch12 - ( (ch10 + ch21)/2 ) Label CP1',  'nch13 = ch13 - ( (ch10 + ch21)/2 ) Label Pz',  'nch14 = ch14 - ( (ch10 + ch21)/2 ) Label P3',...
  'nch15 = ch15 - ( (ch10 + ch21)/2 ) Label P7',  'nch16 = ch16 - ( (ch10 + ch21)/2 ) Label O1',  'nch17 = ch17 - ( (ch10 + ch21)/2 ) Label Oz',...
  'nch18 = ch18 - ( (ch10 + ch21)/2 ) Label O2',  'nch19 = ch19 - ( (ch10 + ch21)/2 ) Label P4',  'nch20 = ch20 - ( (ch10 + ch21)/2 ) Label P8',...
  'nch21 = ch21 - ( (ch10 + ch21)/2 ) Label TP10',  'nch22 = ch22 - ( (ch10 + ch21)/2 ) Label CP6',  'nch23 = ch23 - ( (ch10 + ch21)/2 ) Label CP2',...
  'nch24 = ch24 - ( (ch10 + ch21)/2 ) Label Cz',  'nch25 = ch25 - ( (ch10 + ch21)/2 ) Label C4',  'nch26 = ch26 - ( (ch10 + ch21)/2 ) Label T8',...
  'nch27 = ch27 - ( (ch10 + ch21)/2 ) Label FT10',  'nch28 = ch28 - ( (ch10 + ch21)/2 ) Label FC6',  'nch29 = ch29 - ( (ch10 + ch21)/2 ) Label FC2',...
  'nch30 = ch30 - ( (ch10 + ch21)/2 ) Label F4',  'nch31 = ch31 - ( (ch10 + ch21)/2 ) Label F8',...
  'nch32 = ch32 - ( (ch10 + ch21)/2 ) Label Fp2',  'nch33 = ch33',  'nch34 = ch34'} , 'ErrorMsg', 'popup', 'Warning',...
 'on' );

%Add channel location do on both versions
EEG=pop_chanedit(EEG,'lookup', '/Users/abbiepopa/Documents/MATLAB/eeglab13_4_4b/plugins/dipfit2.3/standard_BESA/standard-10-5-cap385.elp');
%% angry event list 

%create EEG eventlist, run on non-pruned version
EEG  = pop_editeventlist( EEG , 'AlphanumericCleaning', 'on', 'BoundaryNumeric', { -99}, 'BoundaryString', { 'boundary' }, 'ExportEL',...
 'elist_angryDT.txt', 'List', '/Users/abbiepopa/Documents/ERP Analyses/elist_advanced_lister_angry_150820.txt', 'SendEL2', 'EEG&Text', 'UpdateEEG',...
 'on', 'Warning', 'on' );
%% happy event list

%create EEG eventlist, run on non-pruned version
EEG  = pop_editeventlist( EEG , 'AlphanumericCleaning', 'on', 'BoundaryNumeric', { -99}, 'BoundaryString', { 'boundary' }, 'ExportEL',...
 'elist_happyDT.txt', 'List', '/Users/abbiepopa/Documents/ERP Analyses/elist_advanced_lister_happy_150821.txt', 'SendEL2', 'EEG&Text', 'UpdateEEG',...
 'on', 'Warning', 'on' );

%% eDT calm event list

%create EEG eventlist, run on non-pruned version
EEG  = pop_editeventlist( EEG , 'AlphanumericCleaning', 'on', 'BoundaryNumeric', { -99}, 'BoundaryString', { 'boundary' }, 'ExportEL',...
 'elist_calm.txt', 'List', '/Users/abbiepopa/Documents/ERP Analyses/elist_advanced_lister_calm_150821.txt', 'SendEL2', 'EEG&Text', 'UpdateEEG',...
 'on', 'Warning', 'on' ); % GUI: 28-Aug-2016 12:47:19

%% cold DT event list

%create EEG eventlist, run on non-pruned version
EEG  = pop_editeventlist( EEG , 'AlphanumericCleaning', 'on', 'BoundaryNumeric', { -99}, 'BoundaryString', { 'boundary' }, 'ExportEL',...
 'elist_calm.txt', 'List', '/Users/abbiepopa/Documents/ERP Analyses/DT_quickanddirty_advancedelist.txt', 'SendEL2', 'EEG&Text', 'UpdateEEG',...
 'on', 'Warning', 'on' ); % GUI: 28-Aug-2016 12:47:19

%% GNG event list

%create EEG eventlist, run on non-pruned version
EEG  = pop_editeventlist( EEG , 'AlphanumericCleaning', 'on', 'BoundaryNumeric', { -99}, 'BoundaryString', { 'boundary' }, 'ExportEL',...
 'elist_GNG.txt', 'List', '/Users/abbiepopa/Documents/ERP Analyses/elist_adv_GNG.txt', 'SendEL2', 'EEG&Text', 'UpdateEEG', 'on', 'Warning',...
 'on' ); % GUI: 30-Aug-2016 15:46:44
%% all ERPs
%extract bin based epochs
EEG = pop_epochbin( EEG , [-200.0  800.0],  'pre');

%blink rejections
EEG  = pop_artblink( EEG , 'Blinkwidth',  400, 'Channel',  34, 'Crosscov',  0.7, 'Flag', [ 1 2], 'Twindow',...
 [ -200 200] );

%stepwise rejections
EEG  = pop_artstep( EEG , 'Channel',  33, 'Flag', [ 1 3], 'Threshold',  100, 'Twindow', [ -200 200], 'Windowsize',  200, 'Windowstep',...
  50 );

%export e-list manually
%save file manually
%open ICA pruned file
%import elist
eeglab redraw
